"""core.py — the per-invocation Context: root + config + graph adapter.

A documate command runs against one repo (or one sub-tree of a monorepo). The CLI
resolves the root, loads its config, wires the graph adapter, and hands this Context to
every command. No import-time globals — the same process can point at different roots,
and nothing is hard-bound to one checkout.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from .config import Config, load_config
from .graphdb import GraphDB

# First line of every generated page. (The wording predates the one-command
# CLI; changing it would orphan every already-stamped page, so it stays.) Shared here so the anchor scanner
# can tell the generated tier (skip: freshness-checked by regeneration, and a docstring
# quoted into a page may contain example anchors) from authored pages (scan).
GENERATED_STAMP = (
    "<!-- generated by `documate docs` — edit the source, not this file -->"
)


def resolve_root(root: str | Path | None = None) -> Path:
    """Explicit path wins; else the git toplevel of cwd; else cwd (non-git trees)."""
    if root:
        return Path(root).resolve()
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        return Path(out)
    except Exception:
        return Path.cwd()


@dataclass
class Context:
    """Per-invocation bundle: resolved root, loaded Config, wired graph adapter. No import-time globals."""

    root: Path
    config: Config
    graph: GraphDB

    @classmethod
    def make(cls, root: str | Path | None = None) -> "Context":
        """Resolve the root, load its config, and wire a GraphDB into a ready Context."""
        r = resolve_root(root)
        cfg = load_config(r)
        return cls(r, cfg, GraphDB(r, cfg.graph_db, cfg.skip_dirs))

    def rel(self, abspath: str) -> str:
        """Strip the absolute root off a graph path (file or `<abspath>::scope`),
        returning a repo-relative POSIX path. Idempotent on already-relative input."""
        head = abspath.split("::", 1)[0]
        tail = abspath[len(head) :]  # "" or "::scope"
        try:
            rel = Path(head).relative_to(self.root).as_posix()
        except ValueError:
            rel = head
        return rel + tail
